### ISSUE TITLE
ipfs.files.ls() with long option doesn't include type, size, hash 

### ISSUE THREAD

**Issue by ksvirsky** [ipfs/js-ipfs-http-client#1049]
Hi!
The following code snippet was used to list files:
```
const files = await ipfs.files.ls('/', {long: true});
console.log(files);

```
It produces the following result:
```
[
  { name: 'TestFile', type: 0, size: 0, hash: '' },
  { name: 'dir01', type: 0, size: 0, hash: '' },
  { name: 'dir02', type: 0, size: 0, hash: '' },
  { name: 'new1', type: 0, size: 0, hash: '' }
]
```
AFAIU **type, size** and **hash** should be included in response because long option is set.

**Comment by alanshaw** [comment]
What version IPFS node are you communicating with?

**Comment by ksvirsky** [comment]
ipfs version 0.4.21

**Comment by alanshaw** [comment]
Short answer is that go-ipfs doesn't support "long", but if you pass "l" it will work.

Follow along https://github.com/ipfs/go-ipfs#issuecomment-392477565 for progress on adding the longhand option name.

**Comment by alanshaw** [comment]
Sent a PR to fix https://github.com/ipfs/go-ipfs/pull/6528
