### ISSUE TITLE
Content disposition for file parts in uploads should be form-data

### ISSUE THREAD

**Issue by Stebalien** [ipfs/js-ipfs-http-client#1072]
See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition#As_a_header_for_a_multipart_body.

Relates to https://github.com/ipfs/go-ipfs/issues/3322.

(note: go-ipfs doesn't care one way or the other but it now sends form-data)

**Comment by alanshaw** [comment]
This should have been resolved in https://github.com/ipfs/js-ipfs-http-client/pull/948 please re-open if something is not working as expected.
