### ISSUE TITLE
Remove gh urls from dependencies

### ISSUE THREAD

**Issue by achingbrain** [ipfs/js-ipfs-http-client#1122]
We have two deps that are pointing to gh repos.  This can cause people to have problems using this module, like https://github.com/ipfs-shipyard/npm-on-ipfs/issues/117

@hugomrdias if the changes you've made to these modules aren't going to get merged, could you just publish your forks under a different name?

**Comment by achingbrain** [comment]
Another person encountering the same issue: https://github.com/ipfs/js-ipfs-http-client/issues/1139

**Comment by alanshaw** [comment]
🙏 yes please!

**Comment by alanshaw** [comment]
These are both (`concat-stream` & `ndjson`) likely to be removed in the async/await refactor
