### ISSUE TITLE
callback after connection to ipfs 

### ISSUE THREAD

**Issue by HamzaBinSarfraz** [ipfs/js-ipfs-http-client#1135]
```
const ipfsClient = require('ipfs-http-client');

const ipfs = new ipfsClient({
    host: 'ipfs.infura.io',
    port: 5001,
    protocol: 'https'
});

```

is there any callback which confirm me that i am successfully connected to ipfs ?

**Comment by achingbrain** [comment]
No, because the client doesn't make any requests to the node until API methods are invoked.

If you want to confirm the config is valid and you can communicate with the node, you could call a cheap API method after construction like `ipfs.id()`?

**Comment by alanshaw** [comment]
Hope that answeres your question @HamzaBinSarfraz - let us know if not.

**Comment by HamzaBinSarfraz** [comment]
Indeed, Thanks @achingbrain @alanshaw
