### ISSUE TITLE
Need some help I try to npm install --save ipfs-http-client

### ISSUE THREAD

**Issue by Alvan98** [ipfs/js-ipfs-http-client#1139]
Need some help please . I get these error 
![D431FF19-6E65-4FC1-BBC0-1CAAF9837583](https://user-images.githubusercontent.com/57293869/68074092-4e4adf80-fdd2-11e9-8c2a-c76c091ebb5f.png)

**Comment by achingbrain** [comment]
Please ensure you have git installed and that it’s on your path.

See: https://stackoverflow.com/questions/56987664/npm-err-enoent-undefined-when-running-npm-install

**Comment by Alvan98** [comment]
Thanks mate problem solve!!! Thank you Very Much
