### ISSUE TITLE
Bad tag?

### ISSUE THREAD

**Issue by michaelsbradleyjr** [ipfs/js-ipfs-http-client#1175]
![image](https://user-images.githubusercontent.com/194260/69460808-a5413600-0d3a-11ea-9272-68fff23b4bad.png)

**Comment by achingbrain** [comment]
Yes: https://github.com/ipfs/aegir/issues/471

I think @alanshaw was going to remove the rogue tag as it’s only on github, not a release on npm.

**Comment by alanshaw** [comment]
It gone
