### ISSUE TITLE
Migration of License from MIT to Dual MIT/Apache2.0

### ISSUE THREAD

**Issue by ay2306** [ipfs/js-ipfs-http-client#1177]
Creating this issue to migrate the license from MIT only to dual MIT/Apache2.0 as done in [JS-IPFS](https://github.com/ipfs/js-ipfs/pull/2620) and [go-ipfs](https://github.com/ipfs/go-ipfs/pull/6301).

**Comment by ay2306** [comment]
@alanshaw I am taking the issue.

**Comment by sarthak0906** [comment]
Hey can I work in this?

**Comment by ay2306** [comment]
@sarthak0906 yes, you can work on this issue. @alanshaw I hope there is no problem.
