### ISSUE TITLE
Not working on Node.js 13

### ISSUE THREAD

**Issue by AliMirlou** [ipfs/js-ipfs-http-client#1194]
Any calls to the API is dropped and the output is always empty.

After some digging through the code, I realized that commenting this line of code, which seems to be only destroying a clone, solves the problem:
https://github.com/ipfs/js-ipfs-http-client/blob/f77819c4c366a471c22bb6de08a2b133c835cf43/src/lib/error-handler.js#L21

But although it should not, It seems to be causing the whole client to always fail silently. Any ideas?

I'm using ipfs-http-client version 40.0.1 (latest) on Node.js 13.2.0 on Windows 10 v1909 (also tested on Ubuntu Server 18.04).

**Comment by alanshaw** [comment]
Ah thanks for the debugging @AliMirlou! I haven't had a sec to look into this yet but this is helpful. We test on Node.js 10 and 12 right now so I recommend downgrading if you can.

Otherwise, if you're able to help debug this further I'd really appreciate it!

**Comment by AliMirlou** [comment]
It's fixed in Node.js 13.7.0. Don't know what the problem was exactly but it was on their side, not the libraries.

Guessing it had to do something with this pull:
https://github.com/nodejs/node/pull/31314
