### ISSUE TITLE
There is an Alex in my Chrome browser...

### ISSUE THREAD

**Issue by xmaysonnave** [ipfs/js-ipfs-http-client#1202]
Hi Guys,
I noticed the following behaviour in my Chrome browser.
I load from jsedelivr ipfs-http-client. I let you see what I noticed in the following screenshot.
Any explanations...
Thanks
![ksnip_20191217-164130](https://user-images.githubusercontent.com/20576132/70990789-462dd180-20ec-11ea-9c6d-a6b07689d4e7.png)

**Comment by achingbrain** [comment]
Aegir has source maps turned on for production builds - it's going to be removed, see https://github.com/ipfs/aegir/issues/483 for tracking.

**Comment by xmaysonnave** [comment]
Thanks for your fast and clear reply.
