### ISSUE TITLE
0.40.1 does not print anything

### ISSUE THREAD

**Issue by hacdias** [ipfs/js-ipfs-http-client#1210]
Code:

```js
#!/usr/bin/env node
const ipfsClient = require('ipfs-http-client')
;(async () => {
  const ipfs = ipfsClient('/ip4/127.0.0.1/tcp/5001')
  console.log(await ipfs.id())  
})()
```

Running with 0.40.x does not print anything.
Running with 0.39.x works.

**Comment by nhynes** [comment]
have you tried using `ipfsClient({ apiAddr: '/ip4/127.0.0.1/tcp/5001'})`? the config param changed a bit in the new version

**Comment by hacdias** [comment]
I did :)

**Comment by nhynes** [comment]
what about your node version? `v13` doesn't work for some reason. (I just ran into this bug, actually :)

**Comment by hacdias** [comment]
Also 13

**Comment by alanshaw** [comment]
Looks like a dupe of https://github.com/ipfs/js-ipfs-http-client/issues/1194 - any help you can offer would be greatly appreciated!

**Comment by hacdias** [comment]
Yes, it seems to be a duplicate! I'll close this one then.

I'll see if I can do anything. I'm really busy this month with exams :'( starting on the 3rd already
