### ISSUE TITLE
Add tests for buffer: true

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs/js-ipfs-http-client#142]

**Comment by diasdavid** [comment]
More context here would help someone that would like to contribute, to do so.

**Comment by diasdavid** [comment]
@dignifiedquire could update this issue?

**Comment by dignifiedquire** [comment]
There is an option of `buffer` that should turn all methods that default to stream based methods to return the fully buffered version when set to `true`. We don't test this functionality currently.

**Comment by PascalPrecht** [comment]
@diasdavid is this still something that should be addressed?

I can give this a spin. Will have to figure out what and how to test this, but I'm happy to get my feet wet with it with some guidance/pointers :)

**Comment by achingbrain** [comment]
We've largely switched to streaming everything APIs so I'm not sure we want to support buffering anything within the client any more.  The user can use the [`it-all`](https://www.npmjs.com/package/it-all) module to buffer outside of the http api client if required.
