### ISSUE TITLE
`createAddStream` test fails on Travis CI

### ISSUE THREAD

**Issue by daviddias** [ipfs/js-ipfs-http-client#572]
Only reproducible on Travis (works locally and on Circle)

**Comment by nunofmn** [comment]
Sometimes I got the test failing locally also.

**Comment by VictorBjelkholm** [comment]
What I can see it's failing on Travis and Circle ( https://travis-ci.org/ipfs/js-ipfs-api/jobs/247587662 and https://circleci.com/gh/ipfs/js-ipfs-api/1228 ). Most probably a performance issue, so we might want to try to increase the timeout for that test, decrease the amount of data the test uses and/or optimize the function to be faster.

**Comment by diasdavid** [comment]
80000ms should be more than enough and the disparity between seeing success and failing suggests that there something that is not happening rather than happening late. It should be a typical streams race condition.

**Comment by diasdavid** [comment]
![image](https://user-images.githubusercontent.com/1211152/28495462-31400f20-6f02-11e7-9421-5025ea43c2b2.png)

Travis is now looking good :)

**Comment by diasdavid** [comment]
And now it is Circle..

![image](https://user-images.githubusercontent.com/1211152/28495508-99a4d130-6f03-11e7-8bba-5b1bdddbbd56.png)

**Comment by diasdavid** [comment]
fixed with - https://github.com/ipfs/js-ipfs-api/commit/335490135cbe87c352fe675443a9c796aefa50a3

**Comment by diasdavid** [comment]
And it is back

https://travis-ci.org/ipfs/js-ipfs-api/jobs/271122936#L3141-L3143

**Comment by diasdavid** [comment]
Nope, just go-ipfs that got slower and it was timing out the test

**Comment by diasdavid** [comment]
Sometimes it times out 80s, which is a lot. Definitely needs more investigation

**Comment by diasdavid** [comment]
It has been a long day..

**Comment by diasdavid** [comment]
@vmx while you are at it, can you check this one as well?
