### ISSUE TITLE
Speeding up tests

### ISSUE THREAD

**Issue by victorb** [ipfs/js-ipfs-http-client#593]
Note: Let's not spend too much effort on speeding up the tests. I just want to reach a baseline of performance where the tests are not timing out anymore (currently, tests time out for me on Ubuntu with a 3.30GHz processor)

Currently, we're doing some inefficient things in the tests that we can quickly fix to make the tests run a lot faster. Some suggestions from @dignifiedquire in IRC:

* run go-ipfs in offline mode so it doesn't connect to the outside world
* stop respawning the go-ipfs node on every test file. This has the downside of removing clearing the state of the daemon on every test file, but maybe we can do this another way?
* run tests concurrently. Would speed up the general suite of tests but might make individual tests slower as many things are executed at the same time.

**Comment by diasdavid** [comment]
> run go-ipfs in offline mode so it doesn't connect to the outside world

go-ipfs is "offline" for what is worth, MDNS and Bootstrapping is off. 

> stop respawning the go-ipfs node on every test file. This has the downside of removing clearing the state of the daemon on every test file, but maybe we can do this another way?

We've been there. We moved to have tests self contained

**Comment by Kubuxu** [comment]
This is quite important as we would love to run these tests on go-ipfs.
Re: go-ipfs init/startup: use `ipfs init -p test` which makes go-ipfs startup quite a bit faster.

I would say that if these tests were able to run on go-ipfs in less than 5 min it would be feasible to run them on every build but in the current state, I don't see how useful they would be due to a very slow build.

**Comment by alanshaw** [comment]
@Kubuxu that's useful to know!

> Reduces external interference of IPFS daemon, this is useful when using the daemon in test environments.
> https://docs.ipfs.io/reference/api/cli/#ipfs-init

Do you know where I can find more info on what this profile does?

**Comment by Kubuxu** [comment]
And also here, IDK how I missed this notification: https://github.com/ipfs/go-ipfs-config/blob/master/profile.go#L68-L85
