### ISSUE TITLE
Question: Error Invoking put with Links

### ISSUE THREAD

**Issue by nithinkrishna** [ipfs/js-ipfs-http-client#671]
Consider the following example, where I look to create a simple chain of objects. `d1 -> d2 -> d3`. 

```javascript
const ipfs = require('ipfs-api')();
// Create a simple object link chain
// d1 -> d2 -> d3
function getHash(r){
  return r.toJSON().multihash;
};
function $createObj(d, r=null){
  let lk = []
  if(r)
    lk.push({ Hash: getHash(r) })
  return ipfs.object.put({
    Data : new Buffer(d),
    Links: lk
  })
};

$createObj("D3")

.then(function(r){
  console.log("Created D3: " + getHash(r))
  return $createObj("D2", r)
})

.then(function(r){
  console.log("Created D2: " + getHash(r))
  return $createObj("D1", r)
})

.then(function(r){
  console.log("Created D1: " + getHash(r))
})
```

`D3` gets created. However creation of `D2`throws an ` Error: multihashes do not match` error from https://github.com/ipfs/js-ipfs-api/blob/dae62cb38aa17c3b966087e395389c223d1022fc/src/object/put.js#L111.

After a little debugging, I realized that it's happening because the hash returned from https://github.com/ipfs/js-ipfs-api/blob/dae62cb38aa17c3b966087e395389c223d1022fc/src/object/put.js#L70 doesn't match with the one returned from https://github.com/ipfs/js-ipfs-api/blob/dae62cb38aa17c3b966087e395389c223d1022fc/src/object/put.js#L97

Is this happening because I am invoking the `ipfs.object.put` method incorrectly?

**Comment by 6uliver** [comment]
I had the same problem. I figured out that I have to pass name and size too, not just the hash and the size must not be zero. Now it works perfectly for me.

```
ipfs.object.put({
   Data: 'whatever',
   Links: [{
      name: 'linkName',
      hash: hash,
      size: 10,
   }],
});
```

Maybe we should check these fields if they are required and throw a more specific error, for example "Missing field from link: name".

**Comment by daviddias** [comment]
@nithinkrishna Do you still have this issue?

**Comment by achingbrain** [comment]
This issue has grown quite stale, please open a new issue if the problem still exists.
