### ISSUE TITLE
XHR Error in Digital Ocean Node while adding file to ipfs

### ISSUE THREAD

**Issue by sudeepshop** [ipfs/js-ipfs-http-client#682]
Hello Everybody.

I am new to ipfs, but I managed to upload to ipfs from browser using js-ipfs-api (Angular 5). In my localhost it is successfully uploading to ipfs and producing hash using which i can browse the file (https://ipfs.io/ipfs/xxxxxx---hash----xxxxx).

I built the app for production (ng build --prod) and uploaded the files to my digital ocean droplet. http://46.101.14.145/

(I am running ipfs daemon in the server)

But when I select an image to upload the following error is displayed in the console.

`columnNumber: 127331
fileName: "http://46.101.14.145/main.2a2f4f58221778fe8aaf.bundle.js"
lineNumber: 1
message: "XHR error"
stack: "9jcD/</f.prototype._onFinish/p.onerror@http://46.101.14.145/main.2a2f4f58221778fe8aaf.bundle.js:1:127331\nD@http://46.101.14.145/polyfills.a069f9d656035aa74de4.bundle.js:1:31629\neFQL/</</</c</e.prototype.invokeTask@http://46.101.14.145/polyfills.a069f9d656035aa74de4.bundle.js:1:22948\nonInvokeTask@http://46.101.14.145/main.2a2f4f58221778fe8aaf.bundle.js:1:264816\neFQL/</</</c</e.prototype.invokeTask@http://46.101.14.145/polyfills.a069f9d656035aa74de4.bundle.js:1:22861\neFQL/</</</o</t.prototype.runTask@http://46.101.14.145/polyfills.a069f9d656035aa74de4.bundle.js:1:18118\neFQL/</</</u</t.invokeTask@http://46.101.14.145/polyfills.a069f9d656035aa74de4.bundle.js:1:24042\n_@http://46.101.14.145/polyfills.a069f9d656035aa74de4.bundle.js:1:34743\nk@http://46.101.14.145/polyfills.a069f9d656035aa74de4.bundle.js:1:34975\n"`

my config is

`{
  "API": {
    "HTTPHeaders": {
      "Access-Control-Allow-Headers": [
        "X-Requested-With",
	"Range"
      ],
      "Access-Control-Allow-Methods": [
        "PUT",
        "POST",
        "GET"
      ],
      "Access-Control-Allow-Origin": [
        "http://46.101.14.145"
      ]
    }
  },
  "Addresses": {
    "API": "/ip4/127.0.0.1/tcp/5001",
    "Gateway": "/ip4/127.0.0.1/tcp/8080",
    "Swarm": [
      "/ip4/0.0.0.0/tcp/4001",
      "/ip6/::/tcp/4001"
    ]
  },
  "Bootstrap": [
    "/ip4/104.131.131.82/tcp/4001/ipfs/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ",
    "/ip4/104.236.176.52/tcp/4001/ipfs/QmSoLnSGccFuZQJzRadHn95W2CrSFmZuTdDWP8HXaHca9z",
    "/ip4/104.236.179.241/tcp/4001/ipfs/QmSoLPppuBtQSGwKDZT2M73ULpjvfd3aZ6ha4oFGL1KrGM",
    "/ip4/162.243.248.213/tcp/4001/ipfs/QmSoLueR4xBeUbY9WZ9xGUUxunbKWcrNFTDAadQJmocnWm",
    "/ip4/128.199.219.111/tcp/4001/ipfs/QmSoLSafTMBsPKadTEgaXctDQVcqN88CNLHXMkTNwMKPnu",
    "/ip4/104.236.76.40/tcp/4001/ipfs/QmSoLV4Bbm51jM9C4gDYZQ9Cy3U6aXMJDAbzgu2fzaDs64",
    "/ip4/178.62.158.247/tcp/4001/ipfs/QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd",
    "/ip4/178.62.61.185/tcp/4001/ipfs/QmSoLMeWqB7YGVLJN3pNLQpmmEk35v6wYtsMGLzSr5QBU3",
    "/ip4/104.236.151.122/tcp/4001/ipfs/QmSoLju6m7xTh3DuokvT3886QRYqxAzb1kShaanJgW36yx",
    "/ip6/2604:a880:1:20::1f9:9001/tcp/4001/ipfs/QmSoLnSGccFuZQJzRadHn95W2CrSFmZuTdDWP8HXaHca9z",
    "/ip6/2604:a880:1:20::203:d001/tcp/4001/ipfs/QmSoLPppuBtQSGwKDZT2M73ULpjvfd3aZ6ha4oFGL1KrGM",
    "/ip6/2604:a880:0:1010::23:d001/tcp/4001/ipfs/QmSoLueR4xBeUbY9WZ9xGUUxunbKWcrNFTDAadQJmocnWm",
    "/ip6/2400:6180:0:d0::151:6001/tcp/4001/ipfs/QmSoLSafTMBsPKadTEgaXctDQVcqN88CNLHXMkTNwMKPnu",
    "/ip6/2604:a880:800:10::4a:5001/tcp/4001/ipfs/QmSoLV4Bbm51jM9C4gDYZQ9Cy3U6aXMJDAbzgu2fzaDs64",
    "/ip6/2a03:b0c0:0:1010::23:1001/tcp/4001/ipfs/QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd",
    "/ip6/2a03:b0c0:1:d0::e7:1/tcp/4001/ipfs/QmSoLMeWqB7YGVLJN3pNLQpmmEk35v6wYtsMGLzSr5QBU3",
    "/ip6/2604:a880:1:20::1d9:6001/tcp/4001/ipfs/QmSoLju6m7xTh3DuokvT3886QRYqxAzb1kShaanJgW36yx"
  ],
  "Datastore": {
    "BloomFilterSize": 0,
    "GCPeriod": "1h",
    "HashOnRead": false,
    "NoSync": false,
    "Params": null,
    "Path": "/home/sudeep/.ipfs/datastore",
    "StorageGCWatermark": 90,
    "StorageMax": "10GB",
    "Type": "leveldb"
  },
  "Discovery": {
    "MDNS": {
      "Enabled": true,
      "Interval": 10
    }
  },
  "Experimental": {
    "FilestoreEnabled": false,
    "Libp2pStreamMounting": false,
    "ShardingEnabled": false
  },
  "Gateway": {
    "HTTPHeaders": {
      "Access-Control-Allow-Headers": [
        "X-Requested-With",
        "Range"
      ],
      "Access-Control-Allow-Methods": [
        "GET"
      ],
      "Access-Control-Allow-Origin": [
        "*"
      ]
    },
    "PathPrefixes": [],
    "RootRedirect": "",
    "Writable": false
  },
  "Identity": {
    "PeerID": "xxxxx
    "PrivKey": "xxxxxxx"
  },
  "Ipns": {
    "RecordLifetime": "",
    "RepublishPeriod": "",
    "ResolveCacheSize": 128
  },
  "Mounts": {
    "FuseAllowOther": false,
    "IPFS": "/ipfs",
    "IPNS": "/ipns"
  },
  "Reprovider": {
    "Interval": "12h"
  },
  "SupernodeRouting": {
    "Servers": null
  },
  "Swarm": {
    "AddrFilters": null,
    "DisableBandwidthMetrics": false,
    "DisableNatPortMap": false
  },
  "Tour": {
    "Last": ""
  }
}`

You can view my code here: https://github.com/sudeepshop/angularipfs/blob/master/src/app/app.component.ts

What am I doing wrong? Can anyone please help. Thank you.

**Comment by diasdavid** [comment]
@sudeepshop have you set up CORS? https://github.com/ipfs/js-ipfs-api#cors
