### ISSUE TITLE
.files .add a BIG buffer with progress enabled core test is flaky

### ISSUE THREAD

**Issue by vmx** [ipfs/js-ipfs-http-client#726]
The interface core test .files .add a BIG buffer with progress enabled core test is flaky. It fails a lot on CI. I was able to reproduce it locally a few times (not always) with running:

    cpulimit -l 80 -- node ./node_modules/.bin/aegir test -t browser --files test/core/bitswap.spec.js test/core/bootstrap.spec.js test/core/config.spec.js test/core/create-node.spec.js test/core/files-sharding.spec.js test/core/init.spec.js test/core/interface/config.js test/core/interface/files.js

The interesting part is that this test doesn't return the added data (it's an empty array) but also no error.

**Comment by JonKrone** [comment]
Possible case: https://ci.ipfs.team/blue/organizations/jenkins/IPFS%2Fjs-ipfs/detail/PR-1045/16/pipeline/

**Comment by diasdavid** [comment]
@dryajov mind checking ?

**Comment by dryajov** [comment]
checking 👍

**Comment by alanshaw** [comment]
@dryajov did you find anything?

**Comment by dryajov** [comment]
I don't think I was able to reproduce the issue locally, and moved on to serving else. I'll try one more time and report back here.

**Comment by alanshaw** [comment]
related to #748?

**Comment by achingbrain** [comment]
This test hasn't been flaky in a while and the code behind it has changed significantly since this issue was opened.  We'll keep an eye on it but am closing this for now.
