### ISSUE TITLE
Test Back-Pressure

### ISSUE THREAD

**Issue by bvand** [ipfs/js-ipfs-http-client#727]
There are currently no tests confirming that back-pressure is working correctly. We should add such a test so that future changes don't break back-pressure.

The test could "create a dummy API server endpoint that takes a long time to reply and see if the source gets paused when the high water mark is reached" (see https://github.com/ipfs/js-ipfs-api/issues/702).

**Comment by alanshaw** [comment]
@bvand are you working on adding these (as you mentioned in #702)?

**Comment by bvand** [comment]
@alanshaw I haven't done any work on this, feel free to pick it up!

**Comment by achingbrain** [comment]
Everything is async iterators now, which have a back pressure mechanism built in.  Please open a new issue against [ipfs/js-ipfs](https://github.com/ipfs/js-ipfs) if this is still required.
