### ISSUE TITLE
Add timeout for the ipfs api calls

### ISSUE THREAD

**Issue by leonprou** [ipfs/js-ipfs-http-client#781]
I would like to restrict the api call to a certain timeout, and if response not received to have some TimeoutError. Like an HTTP call. Looking into the docs didn't find that option.

**Comment by leonprou** [comment]
@diasdavid hey, what's the `ready` tag means? Maybe I can give a hand in this?

**Comment by diasdavid** [comment]
Thanks for offering to help! The `ready` label comes from Waffle, see https://github.com/ipfs/js-ipfs/blob/master/MGMT.md to learn what which label mean.

This feature needs https://github.com/ipfs/interface-ipfs-core/issues/58 which is the crux to have timeouts.

**Comment by leonprou** [comment]
@diasdavid I did some digging at the code, under the hood you're using the `request` of the `http` module.  This module got a `setTimeout` method.

So I added the following code after:
https://github.com/ipfs/js-ipfs-api/blob/master/src/utils/send-request.js#L165

``` js
    req.setTimeout(timeout, function() {
         console.log('TIMEOUT')
         throw new Error('TIMEOUT')
    })
```

It did throwing an error, so if I'm not missing something we can start with it as a prototype.

**Comment by leonprou** [comment]
@diasdavid hey, any comment?

If the contributors are ok with that approach I'd like to make a PR

**Comment by obo20** [comment]
Are there any updates on this? Such functionality would be super helpful.

**Comment by leonprou** [comment]
@obo20 Eventually I just implemented it with a `Promice.race` and timeout.

You can see it here https://github.com/ColuLocalNetwork/CLN-community-app/blob/master/server/src/utils/metadata.js#L21

**Comment by obo20** [comment]
@leonprou Correct me if I'm wrong, but wouldn't that lead to memory leakage?

It's my understanding that when using Promise.race, the promise that is "timed out" still actually executes code. If the promise never returns, then that memory would effectively be locked wouldn't it? From my research it seems like the js-ipfs-http-client doesn't actually have a way of timing out its own requests so theoretically the request could go on indefinitely, which would lead to memory leakage.

I'm really hoping that I'm wrong on this, and if anybody has a better understanding of this, I'd love to learn more.

@daviddias I was researching  https://github.com/ipfs/js-ipfs-http-client/pull/200 which seems to be focused on letting BluebirdJS promisify all the API calls, but upon trying to do this, I can't utilize the .timeout functionality which is supposedly possible when you primisify api calls using bluebird. (it just says ipfs.pin.add(...).timeout is not a function.  Were there any further changes made to the js-ipfs-http-client that would have broken this functionality?

**Comment by cle1000** [comment]
Hi, 
i found out that go-ipfs has a timeout flag, which is not supported by the ```js-ipfs-http-client```, I modified the code for the cmd ```cat```. Now I can pass a timeout flag to ipfs, see https://github.com/ipfs/js-ipfs-http-client/pull/1034

**Comment by alanshaw** [comment]
Timeouts landed in master today and will be in the next release, see https://github.com/ipfs/js-ipfs-http-client#global-timeouts
