### ISSUE TITLE
block.rm() is missing :(

### ISSUE THREAD

**Issue by mikeal** [ipfs/js-ipfs-http-client#792]
Was surprised to find that this API was missing. It's in the go ipfs command line but isn't in `js-ipfs-api` and isn't documented in https://github.com/ipfs/interface-ipfs-core/blob/master/SPEC/BLOCK.md

**Comment by diasdavid** [comment]
Interesting, this must be new. I remember specifically implementing this endpoint for js-ipfs and then later removing as go-ipfs team was uncomfortable (@whyrusleeping) having a command that would delete something from the store without passing through the pinning/gc.

It seems it got added meanwhile. @whyrusleeping @Stebalien shall we just implement it?

**Comment by whyrusleeping** [comment]
@diasdavid yeah. The command was implemented with the caveat that it do a pin check on that hash. Which makes it *really* slow.

**Comment by whyrusleeping** [comment]
In general, if youre using `ipfs block rm` its *likely* you are doing something wrong.

**Comment by mikeal** [comment]
That's good to know, and should probably be in the docs. It means that, for the specific use case I had for this, it's actually not usable.

**Comment by whyrusleeping** [comment]
Yeah, and i just noticed a typo in the helptext too. Ripe for a PR

**Comment by PascalPrecht** [comment]
Hi,

maybe I can help out with this one. Do I get it right that everybody here agreed `block.rm()` should be implemented?

I'm not super familiar with the `Block` APIs yet, but I can read it up and give it a spin.

**Comment by alanshaw** [comment]
resolved in https://github.com/ipfs/js-ipfs-http-client/pull/1123
