### ISSUE TITLE
js-ipfs-api cann't call ipfs.key.list()

### ISSUE THREAD

**Issue by wanyvic** [ipfs/js-ipfs-http-client#824]
js-ipfs-api: { version: "0.4.17", commit: "acd4b38", repo: "7" }
go-ipfs: version 0.4.17
I want to use the js-ipfs-api to gen a new key to my keypair.
so I make a demo(/js-ipfs-api/examples/bundle-browserify) to list all of my keys,just call func ipfs.key.list()
but error:TypeError: ipfs.key is undefined
console.log(ipfs),I cant find the 'key' function
<img width="703" alt="wx20180802-120731 2x" src="https://user-images.githubusercontent.com/26783673/43562038-c0210506-964c-11e8-9aa6-beb40285ba92.png">
how can I to solve the problem?
thanks for everyone!

**Comment by alanshaw** [comment]
@wanyvic the `ipfs-api` dependency in that example is really old! Try updating to the latest version and you should be able to use that API. Would you be willing to send a PR to update the example?

**Comment by achingbrain** [comment]
This issue is very stale, please open a new one against [ipfs/js-ipfs](https://github.com/ipfs/js-ipfs) if it's still a problem,
