### ISSUE TITLE
ES5 Build Options

### ISSUE THREAD

**Issue by aphelionz** [ipfs/js-ipfs-http-client#830]
We are admittedly being rather extreme in our intentions to support older devices. For example, we have users reporting problems on iOS 10 (complaining about `let`, of all things), and we'd like to support them. Is there a way to use the source code to build a version of js-ipfs-api that

Alternatively, might such a version already exist on a CDN that we can link to?

Thanks!

**Comment by achingbrain** [comment]
This would involve making changes to [aegir](https://github.com/ipfs/aegir) as that's where all the webpack/babel config lives, if it's still desirable.  Please open an issue there.
