### ISSUE TITLE
How can use the P2P API path to send private messages?

### ISSUE THREAD

**Issue by sorleone** [ipfs/js-ipfs-http-client#835]
js-ipfs-api does not seem to provide p2p commands. How can I access these commands? Can you explain how can I extend this library so that I can send encrypted private direct messages? Like sendTo of the ipfs-pubsub-room? They seem to use libp2p dial:

https://github.com/ipfs-shipyard/ipfs-pubsub-room/blob/8fa55b222f904166e6fb98714b078d623ee12d80/src/connection.js#L51

What about the HTTP API path [/p2p/stream/dial](https://ipfs.io/docs/api/#api-v0-p2p-stream-dial) or [/p2p/listener/open](https://ipfs.io/docs/api/#api-v0-p2p-listener-open)?

Currently this is where I am:

    const pkg = require('../package.json');
    const sendRequest = require('ipfs-api/src/utils/send-request')({
      'api-path': '/api/v0/',
      'user-agent': `/node-${pkg.name}/${pkg.version}/`,
      host: 'localhost',
      port: '5001',
      protocol: 'http'
    });

    sendRequest({path: '/p2p/stream/dial'}, (err, result) => {
      console.log(result);
    });

Another question I have is: does `ipfs.util.crypto` supports pipable/pullable crypto streams with AES like Node's `createCipheriv`, and if so how?

**Comment by noxonsu** [comment]
encode your messages using aes

**Comment by magik6k** [comment]
The API is getting refactored - https://github.com/ipfs/go-ipfs/pull/4929. There is a plan to expose separate interface to libp2p streams (https://github.com/ipfs/go-ipfs/issues/5341)

**Comment by zot** [comment]
I started a workaround for this that I talk about in https://github.com/ipfs/js-ipfs-http-client/issues/681#issuecomment-582620203

**Comment by achingbrain** [comment]
If you're still having problems accomplishing this, please ask a question on https://discuss.ipfs.io
