### ISSUE TITLE
addreadblestream file in the alreadycreated IPFS dir

### ISSUE THREAD

**Issue by ekanath25** [ipfs/js-ipfs-http-client#861]
I am creating a dir using mkdir command, i want to add a file in the created dir.

Please help me Thanks in advance

**Comment by alanshaw** [comment]
@ekanath25 check out the [mutable file system commands here](https://github.com/ipfs/interface-ipfs-core/blob/master/SPEC/FILES.md).

You'll probably want to use the [write command](https://github.com/ipfs/interface-ipfs-core/blob/master/SPEC/FILES.md#fileswrite)
