### ISSUE TITLE
proposed Module rename. -api => -http-client

### ISSUE THREAD

**Issue by daviddias** [ipfs/js-ipfs-http-client#892]
Hi! We are considering renaming the IPFS Client libraries, please read more at https://github.com/ipfs/ipfs/issues/374 and comment if you are onboard.

**Comment by achingbrain** [comment]
`-client` makes me think of client/server, which this sort of is, but then people start thinking about HTTP and talking about 'uploading things to IPFS' which derails conversations when you're trying to talk about distributed systems.

Not wanting to bike shed but `-remote` might be better (or not, whatevs) but you're right `-api` sounds like something this is not.

**Comment by daviddias** [comment]
We are going to move with `js-ipfs-http-client` for the next name. @alanshaw please consider this for the next release.

**Comment by alanshaw** [comment]
⚡️ 👍

**Comment by richardschneider** [comment]
So by module rename, do you mean renaming the GitHub repo.  Currently I have https://github.com/richardschneider/net-ipfs-api and should that now be `net-ipfs-http-client`?

Renaming a repo will break all links to the repo and most likely upset any existing forks.  Also how does this effect the package managers and existing software dependent upon the old name?

Any recommended practices on how to go about this?

**Comment by daviddias** [comment]
> Renaming a repo will break all links to the repo and most likely upset any existing forks.

Github is pretty good at redirecting the old name to the new one

> Also how does this effect the package managers and existing software dependent upon the old name?

It is a two step. One deprecates first the old module name and then publishes with the new one.

**Comment by alanshaw** [comment]
> One deprecates first the old module name

FYI https://docs.npmjs.com/cli/deprecate
