### ISSUE TITLE
New IPFS Client Maintainers Group

### ISSUE THREAD

**Issue by mikeal** [ipfs/js-ipfs-http-client#894]
Hiya :)

In the IPFS org we’ve [created a new group](https://github.com/ipfs/community/issues/352#issuecomment-440380041) for maintainers of client libraries. This will make it easier for us to loop you into issues that may cause problems or necessitate changes in your client library.

If you could let us know the github usernames of all the active maintainers we can add them to the group and note them in the [clients table](https://github.com/ipfs/ipfs#http-client-libraries).

Also, we have a great [IPFS weekly newsletter](https://tinyletter.com/ipfsnewsletter). A few days before each edition goes out a new pull request is created [in the repo](https://github.com/ipfs/newsletter). If you have any announcements related to your client library feed free to log a new issue in the repo or just comment on an upcoming newsletter pull request.

**Comment by alanshaw** [comment]
Awesome! I think we're currently @achingbrain @daviddias @hugomrdias and myself.

**Comment by daviddias** [comment]
Anything outstanding to do here?

**Comment by richardschneider** [comment]
Help on https://discuss.ipfs.io/t/grokking-api-v0-get/4420/1 and https://discuss.ipfs.io/t/the-x-headers-in-http-api/4429/1 would be greatly appreciated.
