### ISSUE TITLE
RFC: expose types and utils in static context

### ISSUE THREAD

**Issue by lidel** [ipfs/js-ipfs-http-client#902]
> I just found [this](https://github.com/ipfs/js-ipfs-http-client/issues/406), I'm curious why it was defined based on an instance of ipfs, rather than something static since it points at the statically defined types.
> 
> My specific use case is to do something like `foo instanceof ipfs.types.CID` but it happens in static functions or places where the ipfs instance isn't passed as a variable, i.e. where I don't easily have access to the "ipfs" variable, but have easy access to the result of 
> `IPFS = require('ipfs')`, 
> 
> The current code does `CID=require('cids')` solely to allow this type check, which seems exactly the kind of example this change was intended to avoid.
> 
> _Originally posted by @mitra42 in https://github.com/ipfs/js-ipfs-http-client/issues/406#issuecomment-443955150_

I remember having similar thoughts at least once (had to make fake instance just to access utils).
 
Perhaps we could at least support it in the static context by [exposing data types and util functions](https://github.com/ipfs/js-ipfs-http-client/blob/v27.0.0/README.md#domain-data-types) on `IPFS` (the static constructor) as well.

Thoughts?

**Comment by alanshaw** [comment]
I am already +1 for this (https://github.com/ipfs/js-ipfs/pull/1297#issuecomment-381622843)
