### ISSUE TITLE
Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by Juanchobanano** [ipfs/js-ipfs-http-client#905]
Hey IPFS team, I have a strange error when trying to add new files to IPFS.
Here's my code:

`
    
    const ipfsClient = require('ipfs-http-client');
    const ipfs = ipfsClient("ipfs.infura.io", "5001", {protocol: "http"});

    let testFile = fs.readFileSync("./backend/images/imagen.jpg");
    ipfs.add(testFile, (err, res) => { 
        if(err) { console.error(err); }
    });

`

It always returns the error "SyntaxError: Unexpected token < in JSON at position 0".
The value of testFile variable is " <Buffer ff d8 ff e0 00 10 4a 46 49 46 00 01 01 00 00 01 00 01 00 00 ff fe 00 3b 43 52 45 41 54 4f 52 3a 20 67 64 2d 6a 70 65 67 20 76 31 2e 30 20 28 75 73 69 ... > "

I hope you can help me :(

**Comment by Juanchobanano** [comment]
Hey guys! Sorry for the late response.
This is the way you can reproduce my error: 

`

     const ipfsClient = require("ipfs-http-client");
     const ipfs = ipfsClient({host: "ipfs.infura.io", port: "5001", protocol: "https"})

     app.use("/ipfsBug", (req, res) => {

     // Returns buffer of both files.
     let hash;
     const file1 = fs.readFileSync("./backend/images/imagen.jpg");
     const file2 = fs.readFileSync("./backend/images/imagen2.jpg");
    
     let dataToLoad = [
        {
            path: "backend/images/imagen.jpg",
            content: file1
        },
        {
            path: "backend/images/imagen2.jpg", 
            content: file2
        }
     ];

     ipfs.add(dataToLoad, [{"wrapWithDirectory": true}], (err, data) => {
        if(err){
            console.log(err);
        }else{
            console.log(data);
        }

        folderHash = data[data.length - 1].hash

        console.log("trying to use ipfs.ls function...")

        // Ipfs.ls returns error mentioned above.
        ipfs.ls(folderHash, function(err, files){
            if(err){
                console.log(err);
            }else{
                console.log(files);
            }
        });

        // Ipfs.get returns the files stored correctly.
        ipfs.get(folderHash, function(err, files){
            if(err){
                console.log(err);
            }else{
                console.log(files); 
            }
        });

    });

    /*const validCID2 = 'QmVwrz43zSJ9JqYtVFZovzoTdVRY1rnF62bc1xzDC9NmxL'
    ipfs.get(validCID2, function (err, files) {
        console.log("err :", err);
        console.log("files: ", files);
        files.forEach((file) => {
            console.log(file.path)
        });
    });*/

    res.status(200).json({
        message: "asd"
    })
})
`
Hope this can help!

**Comment by alanshaw** [comment]
```js
ipfs.add(dataToLoad, [{"wrapWithDirectory": true}], (err, data) => {
```

Your options are wrapped in an array, this will probably result in the directory wrapper not being applied...

https://ipfs.io/api/v0/ls?arg=QmNXGopftrhhDcx9zJxBcdWdYm3bGSXQwT9quwB1sDmxX6 is working for me right now.

However your server is returning the response:

```html
<html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

https://ipfs.infura.io:5001/api/v0/ls?arg=QmNXGopftrhhDcx9zJxBcdWdYm3bGSXQwT9quwB1sDmxX6

Hope that helps.

P.S. I've opened [this issue](https://github.com/ipfs/js-ipfs-http-client/issues/912) to track getting better error messages for unexpected responses.

**Comment by Nikhil-Bathula** [comment]
ipfs.get throwing Unexpected token < in JSON at position 0 error

 This is my code

ipfs.get(validCID, async function (err, files) {
      if (err) {
        resolve([])
      } else {
        resolve(files)
      }
    })

I kept this functionality in a loop. Even though i am passsing validCID it is throwing this error.
