### ISSUE TITLE
URL is not a constructor

### ISSUE THREAD

**Issue by mccoysc** [ipfs/js-ipfs-http-client#911]
const requestWithRedirect = (url, opts, sendOneFile, callback) => {
  const parsedUrl = new URL(url)
....
}
add-from-url.js:38 Uncaught TypeError: URL is not a constructor
    at requestWithRedirect (add-from-url.js:38)
    at Function.promisify (add-from-url.js:31)
    at Object.addFromURL (index.js:32)
    at <anonymous>:1:9

if use new window.URL(url),all would be ok.

**Comment by alanshaw** [comment]
this was fixed upstream in `iso-url` - please open a new issue if the problem persists after upgrading to the latest version of `ipfs-http-client`
