### ISSUE TITLE
electron-rebuild fault

### ISSUE THREAD

**Issue by yueleiMaster** [ipfs/js-ipfs-http-client#919]
electron v1.7.11
electron-rebuild v1.8.2
nodejs v8.9.3

When I need to rebuild the program, ipfs-http-client reported an error, which may be related to ursa-optional library. Please help me check, thank you
![image](https://user-images.githubusercontent.com/25242674/50513153-e8663b00-0ad0-11e9-9edb-3cacb7bc3ab0.png)

**Comment by daviddias** [comment]
@ipfs/wg-gui-team any advice for electron users? 

PS: It would be great to have an update for users at https://github.com/ipfs/notes/issues/256

**Comment by alanshaw** [comment]
Hmmm, this is odd, `ursa-optional` should not cause an error on rebuild.

**Comment by olizilla** [comment]
@yueleiMaster can you give us any more info? I've not seen that error before.

**Comment by kav** [comment]
I'm seeing a very similar error, trouble finding headers uRSA needs, on OSX when attempting to import `js-ipfs-http-client` into an `electron-forge` based project which appears to be related to:

https://github.com/JoshKaufman/ursa/issues/161
https://github.com/electron/electron/issues/11801

It would also appear, in comments on those issues, that uRSA can be replaced with native javascript methods in node versions v10.12 and later. Switching to the native methods will land here I believe:
https://github.com/libp2p/js-libp2p-crypto/issues/130

In the meantime; any other solid workarounds? I can monkey patch electron I suppose but I'd love something simpler.

node: 10.15.3 and 12.1.0 
electron-forge: 5.2.4 and 6.0.0-beta.34
electron: 5.0.1

```
An unhandled error has occurred inside Forge:
  CXX(target) Release/obj.target/ursaNative/src/ursaNative.o
In file included from ../src/ursaNative.cc:3:
../src/ursaNative.h:13:10: fatal error: 'openssl/rsa.h' file not found
#include <openssl/rsa.h>
         ^~~~~~~~~~~~~~~
```

**Comment by daviddias** [comment]
@hugomrdias, it is worth sharing an update here https://github.com/ipfs/notes/issues/256

**Comment by hugomrdias** [comment]
This issue is fixed with the latest version and notes are updated https://github.com/ipfs/notes/issues/256#issuecomment-495540554
