### ISSUE TITLE
The equivalence to `ipfs add <directory> -r`

### ISSUE THREAD

**Issue by birbird** [ipfs/js-ipfs-http-client#920]
Hi, what's the equivalence to `ipfs add <directory> -r`
My code is 
```
    let result = await ipfs.add([{
      path: 'C:\\Users\\XXX\\Pictures'
    }], { recursive: true })
```
The response is 
```
[ { path: 'C:\\Users\\XXX\\Pictures',
    hash: 'QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn',
    size: 4 } ]
```
Which is not expected

Could you please help, what's the right way to add directory.
Any help will be highly appreciated.

**Comment by alanshaw** [comment]
You can use `addFromFs` for this! https://github.com/ipfs/interface-ipfs-core/blob/master/SPEC/FILES.md#addfromfs
