### ISSUE TITLE
cannot be imported by Meteor 1.8+

### ISSUE THREAD

**Issue by yuwiggin** [ipfs/js-ipfs-http-client#924]
1. install ipfs-http-client package 
>meteor npm i ipfs-http-client --save

2. Add ipfs.js file with the following

```
const ipfsClient = require('ipfs-http-client')
const ipfs = ipfsClient('localhost', '5001', { protocol: 'http' })
```

3. Then run Meteor,
>meteor

open http://localhost:3000

An error occured in the browser's console
```
Uncaught TypeError: ipfsClient is not a function at ipfs.js
```
Meteor Version: Meteor 1.8.0, 1.8.0.2,  
OS: macOS Sierra V10.12.6,  
ipfs-http-client: 28.1.1,  

What's wrong?

**Comment by yuwiggin** [comment]
this is [a reference from Meteor](https://github.com/meteor/meteor/issues/10411)

**Comment by alanshaw** [comment]
@yuwiggin can you verify with the latest version and close your issue on the meteor repo if resolved?
