### ISSUE TITLE
upload-file-via-browser failed 

### ISSUE THREAD

**Issue by yuwiggin** [ipfs/js-ipfs-http-client#933]
I tested [the example](https://github.com/ipfs/js-ipfs-http-client/tree/master/examples/upload-file-via-browser) but failed.  When a file was selected and open, the console showed the following errors:

```
Uncaught TypeError: Cannot read property 'reading' of undefined at resume_ 
Uncaught TypeError: Cannot read property 'length' of undefined at onwriteDrain at afterWrite
Uncaught TypeError: Cannot read property 'length' of undefined at maybeReadMore_ at afterWrite
Uncaught TypeError: Cannot read property 'endEmitted' of undefined at endReadableNT
```

My running environment:
MacOS: 10.12.6
Node: 8.11.3 
ipfs-http-client: 29.0.0
pull-file-reader: 1.0.2
ipfs instance was set: `this.ipfs = ipfsClient( "ipfs.infura.io", "5001", {protocol: "https"})`

Any Wrong?

**Comment by bmiller59** [comment]
Is there any update on this? I am having the same problem trying to upload a simple buffer from the browser using Infura.  

If there is no fix that will be deployed soon please advise how to mitigate/work around this issue in the short term. Thank you.

**Comment by platoscave** [comment]
+1
same problem

**Comment by w3cshare** [comment]
+1
same problem

**Comment by alanshaw** [comment]
I cannot replicate this at all. Perhaps the infura node was down? @yuwiggin @bmiller59 @platoscave @w3cshare you able to verify this is working now?

**Comment by langelog** [comment]
Adding myself to the thread for status update

**Comment by jzstern** [comment]
Getting identical error messages (but a TON of them, easily over 100) when I simply run my js-ipfs node from my Vue.js app. not using infura or any gateways, and verified my node is up & running with the following snippet:

```javascript
ipfs.id(function (err, identity) {
        if (err) {
          throw err
        }
        console.log(identity)
      })
```

<img width="772" alt="Screen Shot 2019-03-13 at 1 34 51 PM" src="https://user-images.githubusercontent.com/9055087/54315235-330d3480-45a3-11e9-80b9-0484cd472a85.png">

I _think_ I'm still able to retrieve files successfully (not worried about uploading), but I'm worried this issue might be interfering with functionality

**Comment by alanshaw** [comment]
@jzstern do you have a working example you can share that exhibits this issue? Unless I can replicate it I can't help debug.

**Comment by jzstern** [comment]
> @jzstern do you have a working example you can share that exhibits this issue? Unless I can replicate it I can't help debug.

Sorry - forgot about this thread. I switched to importing IPFS via a CDN in my index.html file and that got rid of the errors (: 

```
<script src="https://unpkg.com/ipfs/dist/index.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/ipfs/dist/index.min.js"></script>
```

**Comment by yuwiggin** [comment]
The error is found in the `Readable` class of 
 `node_modules/ipfs-http-client/node_modules/readable-stream/lib/_stream_readable.js`.  and `node_modules/iso-stream-http/node_modules/readable-stream/lib/_stream_writable.js`   The  `ReadableState state` of  `function resume_(stream, state) ` and `function maybeReadMore_(stream, state) `,  and `WritableState state` of `function onwriteDrain(stream, state)` were NOT defined. 

```
function resume_(stream, state) {
  debug('resume', state.reading);

  if (!state.reading) {
    stream.read(0);
  }

  state.resumeScheduled = false;
  stream.emit('resume');
  flow(stream);
  if (state.flowing && !state.reading) stream.read(0);
}
```                             
                               

```
function onwriteDrain(stream, state) {
  if (state.length === 0 && state.needDrain) {
    state.needDrain = false;
    stream.emit('drain');
  }
} // if there's something in the buffer waiting, then process it
```
``` 
function maybeReadMore_(stream, state) {
  while (!state.reading && !state.ended && (state.length < state.highWaterMark || state.flowing && state.length === 0)) {
    var len = state.length;
    debug('maybeReadMore read 0');
    stream.read(0);
    if (len === state.length) // didn't get any data, stop spinning.
      break;
  }

  state.readingMore = false;
} 
```

**Comment by yuwiggin** [comment]
the error was found in the following  function `resume` in the file `node_modules/ipfs-http-client/node_modules/readable-stream/lib/_stream_readable.js`

```
function resume(stream, state) {
  if (!state.resumeScheduled) {
    state.resumeScheduled = true;
      console.log('state', state)
    process.nextTick(resume_, stream, state);
  }
}
``` 

the `state` was defined before  `process.nextTick` was called, but it is undefined when `resume_` is called. What happened? 

On the other side, at least 3 modules `readable-stream` are imported into my project. Any version conflicts? 

Can anyone solve this problem?

**Comment by alanshaw** [comment]
@yuwiggin v35 has a new implementation for add that uses the `fetch` API. I'm going to close this issue because the error messages are no longer refer to any code in the module. If you have problems uploading again please open a new issue.
