### ISSUE TITLE
Does not work on Chrome for iOS mobile, safari for iOS mobile

### ISSUE THREAD

**Issue by projectoblio** [ipfs/js-ipfs-http-client#941]
I required this dependency in another library and, after using browserify, I wasn't able to have the file load in Chrome for iOS and Safari for iOS. I wasn't doing anything with the library yet. It simply wasn't building; the object couldn't be built within the browser. It was working for Desktop Chrome, Android Chrome, and Desktop Firefox. 

 I wasn't able to pinpoint the error. It seemed to point to a code line containing an ellipse ( "..." ) as an error, but I'm not sure how this could be correct.  However, someone with a Mac should double-check whether they can reproduce this error.

It is only possible to debug safari on a mobile Apple device. You can't debug chrome. So, hopefully, if it works on mobile Apple device's Safari, it will also work in mobile Apple device's Chrome.

**Comment by alanshaw** [comment]
@projectoblio what versions of these browsers are you using? Arrow functions are supported in both according to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#Browser_compatibility

Can you share with us some code that exhibits this error when used in these browsers and are you able to take a screenshot or copy the error message?

**Comment by projectoblio** [comment]
Thanks. I didn't realize I would need a babel es2015 extension to browserify to compile this library (and most other modern libraries). I will close this issue now.
