### ISSUE TITLE
IPFS returning bad gateway

### ISSUE THREAD

**Issue by kwakwaa** [ipfs/js-ipfs-http-client#953]
Hello,

Sometimes when I'm adding files to IPFS I get an error trying to access them, basically when opening the page 'https://ipfs.io/ipfs/Qm(...)' it returns some nginx 504 bad gateway error, I've looked around and tried some solutions, tried the CORS thing just to be sure, tried opening exceptions on my firewall, tried mirrors and whatever else I could find online but nothing... It maybe works fine 1 out of 5 times I try it.

The error:
![image](https://user-images.githubusercontent.com/43790012/53891189-bcf85300-4021-11e9-8bd2-e79106754096.png)

Daemon seems to be working fine:
![image](https://user-images.githubusercontent.com/43790012/53890986-4196a180-4021-11e9-9ca5-57a0d0de9327.png)

This is what my code looks like (pretty basic) and it's uploading fine...
![image](https://user-images.githubusercontent.com/43790012/53891057-668b1480-4021-11e9-9aab-e55b8b1dff27.png)

I can access the content fine on 'http://localhost:8080/ipfs/Qm(...)' it's just online that it doesn't work... 

Any ideas why this is happening or something else I could try ? 

Thank you so much for your time!

**Comment by alanshaw** [comment]
This is an issue with the gateway nodes that IPFS runs. Sometimes they are down for maintenance or are too busy but they usually become available again within a few minutes. I don't think there's currently any guarantees on availability for the gateways so currently if you need that then the only option is to run your own gateway.
