### ISSUE TITLE
upload-file-via-browser example does not work with Infura gateway and large files

### ISSUE THREAD

**Issue by rori4** [ipfs/js-ipfs-http-client#958]
I tested the example and Chromium crashed as the file was too big. The file that I tried to upload was around 400MB

EDIT:
The crash of the browser happens only when I try to use the public infura gateway.
`({ host: 'ipfs.infura.io', port: 5001, protocol: 'https' });`
On localhost it has no problem. The upload on infura works when I try small files but makes the browser crash when I try to use a big file.

Chromium version: Version 73.0.3683.86 (Official Build) (64-bit)

_Originally posted by @rori4 in https://github.com/ipfs/js-ipfs-http-client/pull/884#issuecomment-475873908_

**Comment by alanshaw** [comment]
@rori4 are you sure this is a problem with big/small files and not just the issue described here https://github.com/ipfs/js-ipfs-http-client/issues/959?

**Comment by vasa-develop** [comment]
I have also faced this issue. In fact, every service that uses infura has this issue. So, I had to shift to our own servers to resolve this issue. It works fine on our remote nodes.
@rori4 can you shoot the error logs here? It may be the case that we are facing different issues.

**Comment by rori4** [comment]
There is not error whatsoever. The browser just crashes because it is out of memory. It gives the message "Aw, Snap!" for the Chrome browser.  I really don't know where to find a crash log or something for this. Is there a way to log what caused the crash?

**Comment by alanshaw** [comment]
I'm going to close this as the `ipfs.add` code has been refactored to use the browser `fetch` API. Please open a new issue if you're still seeing this.
