### ISSUE TITLE
Uncaught TypeError: Buffer is not a function at FileReader.reader.onloadend

### ISSUE THREAD

**Issue by ask03** [ipfs/js-ipfs-http-client#962]
I am using the ipfs-http-client CDN in my project and I defined Buffer using the built in Buffer in the client.  My code looks like this : 

`const Buffer = window.IpfsHttpClient().Buffer`

The above line of code is on the first line in my js file.  This exact unchanged code was working three weeks ago, but I'm just stumped as to why all of a sudden it isn't working.

The part of my project where Buffer is called is : 
```
  loadImg: function(event) {
  console.log("capture and load img...");
  const file = event.files[0];
  const reader = new window.FileReader();
  reader.readAsArrayBuffer(file)
  reader.onloadend = () => {
    App.imgBuffer = Buffer(reader.result);
    console.log('buffer', App.imgBuffer);
  }
}
```

This exact code was working three weeks ago.

**Comment by alanshaw** [comment]
In v30 the exported `Buffer` constructor moved from `window.IpfsHttpClient().types.Buffer` to `window.IpfsHttpClient.Buffer` https://github.com/ipfs/js-ipfs-http-client/blob/master/CHANGELOG.md#3000-2019-03-13

See it working here: https://jsbin.com/zegetiy/edit?html,console
