### ISSUE TITLE
add with 1MB file triggers Uncaught Error: stream.push() after EOF

### ISSUE THREAD

**Issue by olizilla** [ipfs/js-ipfs-http-client#967]
Uploading a file > 1MB, as a pull-stream fails, with the error:

```
Uncaught Error: stream.push() after EOF
    at new NodeError (errors-browser.js:30)
    at readableAddChunk (_stream_readable.js:269)
    at PullDuplexStream.push../node_modules/readable-stream/lib/_stream_readable.js.Readable.push (_stream_readable.js:240)
    at next (index.js:55)
    at FileReader.loaded (index.js:22)
```

The issue is occuring in master on webui.ipfs.io since upgrading v30.1.2 from v29.1.0

See: https://github.com/ipfs-shipyard/ipfs-webui/issues/1010

**Comment by olizilla** [comment]
Also of note, in ipfs-webui we use https://github.com/tableflip/pull-file-reader

which has a default chunk size of 1MB https://github.com/tableflip/pull-file-reader/blob/master/index.js#L8 which suspiciously conincides with the threshold for triggering this issue.

**Comment by olizilla** [comment]
@hugomrdias this is blocking a relase of webui and desktop. Are you digging in to it or should I jump on it?

**Comment by olizilla** [comment]
investigating this some more...

- [we dont test `ipfs.add` in the browser](https://github.com/ipfs/js-ipfs-http-client/blob/17d49de29b634d0f485dd49a553adbb518194d37/test/interface.spec.js#L104-L118) due to https://github.com/ipfs/go-ipfs/issues/4078
- issue can be recreated in with the `upload-file-via-browser` example in this repo

<img width="897" alt="Screenshot 2019-04-18 at 11 55 48" src="https://user-images.githubusercontent.com/58871/56356553-0e733080-61d1-11e9-9eb0-51fa590e4b3b.png">

**Comment by hugomrdias** [comment]
im on it, will report back asap

**Comment by olizilla** [comment]
@hugomrdias I'm on it. The problem seems to be in pull-file-reader

**Comment by olizilla** [comment]
There is nothing in pull-stream-reader to stop it from emitting the `cb(true)` for when the offset exeeds the filesize, while it is still waiting for a data callback from the FileReader...

<img width="897" alt="Screenshot 2019-04-18 at 12 28 03" src="https://user-images.githubusercontent.com/58871/56358112-94917600-61d5-11e9-922d-446ea3379c9a.png">

in the above, with a 2Mb file, we see it trigger the offset > filesize callback before the final data chunk.

**Comment by hugomrdias** [comment]
But this worked before right? what changed in ipfs to trigger this problem?

**Comment by olizilla** [comment]
It sure did! I think something else must have been dealing with it, when it should always have been an error. I just added a quick, "_count the pending chunks_" check to pull-stream-reader and it fixes it! Will PR a cleaner fix now.

**Comment by olizilla** [comment]
<img width="898" alt="Screenshot 2019-04-18 at 12 37 28" src="https://user-images.githubusercontent.com/58871/56358532-c5be7600-61d6-11e9-8e17-3749aba5b8c5.png">

**Comment by olizilla** [comment]
@hugomrdias oh no wait, you are right, this is super weird, the pull-stream sink should not be asking for more chunks before it gets a callback from the previous one... that's the weirdness that is causing this. I could guard against it in pull-file-reader, but it seems like we have a rogue pull-stream sink in ipfs now that is just pulling as fast as it can, rather than waiting for each chunk

**Comment by olizilla** [comment]
Moved the guard to pull-to-stream, and we have a fix! https://github.com/hugomrdias/pull-to-stream/pull/1
