### ISSUE TITLE
urlstore support

### ISSUE THREAD

**Issue by mitra42** [ipfs/js-ipfs-http-client#969]
Is there some reason that the `urlstore` http api is not supported ?  See https://docs.ipfs.io/reference/api/http/#api-v0-urlstore-add 

I believe a similar question applies in js-ipfs, but understand that might be a deeper issue. 

(Ideally I want to call `ipfs.urlstore` or similar and have it work in both the `js-ipfs-http-client` and in `js-ipfs` so that higher layers don't have to know whether they are running the client, or connected via the API.)

**Comment by alanshaw** [comment]
> Is there some reason that the `urlstore` http api is not supported?

Not so much not supported, more not implemented yet ;)

**Comment by alanshaw** [comment]
Looks like this is going away https://github.com/ipfs/go-ipfs/pull/6223/files#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR52

**Comment by mitra42** [comment]
Sounds like it ... but the question still applies since nostore isn't mentioned as an option on https://github.com/ipfs/interface-js-ipfs-core/blob/master/SPEC/FILES.md#add 
Do you want to rename/reopen this issue, or should I add a new one ?

**Comment by alanshaw** [comment]
There's an issue open for `nocopy` here https://github.com/ipfs/js-ipfs-http-client/issues/963 but there needs to be one in https://github.com/ipfs/js-ipfs/issues for adding filestore. If you don't mind opening one there it would be appreciated!

**Comment by mitra42** [comment]
Done https://github.com/ipfs/js-ipfs/issues/1999
