### ISSUE TITLE
the progress work slowly

### ISSUE THREAD

**Issue by ShareTheWorld** [ipfs/js-ipfs-http-client#971]
ipfs-htt-client, this progress bar works slowly.
I add a file to ipfs via the add（） method, but I need to wait a long time before it call back the progress.
Just like the progress is called after the upload is completed.
Code
```
<script src="https://unpkg.com/ipfs-http-client/dist/index.js"></script>
Var file = files.files[0];
Var ipfs = IpfsHttpClient({host: '95.* *.201.* *', port: '5001', protocol: 'http'});
Var a = '';
For (var i = 0; i < 500000; i++) a += 'aaaaaaaaaa';
Const content = co.stringToBuffer(a);
Ipfs.add(content, {
Progress: function (p) {
Console.log(p);
},
chunkSize: 10 * 1024 * 1024
}).then(function (result) {
Console.log(result);
}).catch(function (err) {
Console.log(err);
});
```

Just like the progress is called after the upload is completed?this is problem

**Comment by ShareTheWorld** [comment]
![Screenshot from 2019-04-16 19-57-17](https://user-images.githubusercontent.com/9106459/56208000-ae6e7400-6082-11e9-89b5-6621033a54d8.png)

this is network information

**Comment by alanshaw** [comment]
Yes, the progress function is called as IPFS ingests data. Browsers do not support streaming uploads natively yet so you'll only start to get progress once the request has been sent.
