### ISSUE TITLE
concat-stream

### ISSUE THREAD

**Issue by arietrouw** [ipfs/js-ipfs-http-client#977]
Please use the npmjs version of concat-stream.  Currently, the project refers to "concat-stream hugomrdias/concat-stream#feat/smaller" which causes problems on some CI/CD platforms (DepShield).  Also, it is better to use npmjs since it does not change.

**Comment by alanshaw** [comment]
Blocked by https://github.com/maxogden/concat-stream/pull/62

**Comment by alanshaw** [comment]
Lets track this in #1122 now
