### ISSUE TITLE
The current transaction exceeded its quota limitations.

### ISSUE THREAD

**Issue by ishanjoshi02** [ipfs/js-ipfs-http-client#979]
**Severity**: Medium
**IPFS Version**: `0.4.19`
**Platform**: Windows 64bit (Running Windows 10)
**Browser**: Mozilla Firefox (Version: 66.0.3)

I am uploading a 9 MB video file to IPFS, using code

```js
const buffer = Buffer.from(<filepath>)
node.add(buffer, (err, files)=>{if (err) { console.log(err) }})
```

**Comment by alanshaw** [comment]
@ishanjoshi02 did you solve the issue? If not, where do you see this error logged? - In Firefox? Do you have a stack trace and can you share the file you're trying to upload so we can replicate it?

**Comment by ishanjoshi02** [comment]
I have solved the bug.
Was an issue on my side.
