### ISSUE TITLE
Accept ArrayBuffer alongside the Buffer to ease the adoption

### ISSUE THREAD

**Issue by marsrobertson** [ipfs/js-ipfs-http-client#982]
Docs: https://github.com/ipfs/interface-js-ipfs-core/blob/master/SPEC/FILES.md#add

See here: https://github.com/feross/buffer/issues/229

So I need to include extra package.

And then I need to figure out how to convert string:
* https://developers.google.com/web/updates/2012/06/How-to-convert-ArrayBuffer-to-and-from-String
* https://stackoverflow.com/questions/6965107/converting-between-strings-and-arraybuffers

It's getting pretty messy pretty quickly.

**Comment by alanshaw** [comment]
You can use File objects as of v31.1.0 - does that help?

**Comment by marsrobertson** [comment]
When I have time (probably never or in 2 years) I'll check things out.

In the meanwhile, built a suite of tools to workaround: https://github.com/genesisdotre/kleros-metaevidence-metahash

**Comment by alanshaw** [comment]
Also, `Buffer` is exported from `ipfs-http-client` so you can do:

```js
const IpfsHttpClient = require('ipfs-http-client')
const data = IpfsHttpClient.Buffer.from('your string')
const ipfs = IpfsHttpClient('/ip4/127.0.0.1/tcp/5001')
ipfs.add(data, console.log)
```

Or in the browser:

```html
<script src="https://unpkg.com/ipfs-http-client/dist/index.min.js"></script>
<script>
const data = window.IpfsHttpClient.Buffer.from('your string')
const ipfs = window.IpfsHttpClient('/ip4/127.0.0.1/tcp/5001')
ipfs.add(data, console.log)
</script>
```

https://github.com/ipfs/js-ipfs-http-client#static-types-and-utils

Adding a file should be as easy as:

```html
<input type="file" id="upload">
<script src="https://unpkg.com/ipfs-http-client/dist/index.min.js"></script>
<script>
const ipfs = window.IpfsHttpClient('/ip4/127.0.0.1/tcp/5001')
document.getElementById('upload').addEventListener('change', e => {
  ipfs.add(e.target.files[0], console.log)
})
</script>
```
