### ISSUE TITLE
Should the required NodeJS version be >=8.0.0?

### ISSUE THREAD

**Issue by michaelsbradleyjr** [ipfs/js-ipfs-http-client#983]
See: https://github.com/ipfs/js-ipfs-http-client/pull/937#issuecomment-486422623.

**Comment by michaelsbradleyjr** [comment]
ping

**Comment by michaelsbradleyjr** [comment]
ping

**Comment by alanshaw** [comment]
This is not a priority for us as we've decided our minimum supported version is Node.js 10. That said, I see no reason to deny Node.js 8 users from installing if it is still compatible, so if you're willing to help @andremedeiros with https://github.com/ipfs/js-ipfs-http-client/pull/937#issuecomment-491733784 that would be amazing.

**Comment by michaelsbradleyjr** [comment]
Sounds great, thanks.
